export const spotData = [
  {
    id: 1,
    name: "Mar del Plata",
    image: "https://images.unsplash.com/photo-1523712999610-f77fbcfc3843?w=800",
    address: "Costa Atlántica, Buenos Aires, Argentina",
    weather: "Templado oceánico, veranos cálidos e inviernos suaves",
    activities: "Playas, casino, golf, pesca deportiva, vida nocturna, lobería",
    accommodationPrice: 45000,
    location: "https://maps.google.com/?q=-38.0055,-57.5426",
  },
  {
    id: 2,
    name: "Villa Carlos Paz",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
    address: "Valle de Punilla, Córdoba, Argentina",
    weather: "Templado serrano, veranos cálidos y secos",
    activities: "Lago San Roque, sierras, parapente, teatros, vida nocturna, deportes náuticos",
    accommodationPrice: 38000,
    location: "https://maps.google.com/?q=-31.4208,-64.4990",
  },
  {
    id: 3,
    name: "Bariloche",
    image: "https://images.unsplash.com/photo-1589802829985-817e51171b92?w=800",
    address: "Patagonia, Río Negro, Argentina",
    weather: "Frío de montaña, nevadas en invierno",
    activities: "Ski, snowboard, senderismo, chocolaterías, Lagos Nahuel Huapi y Gutiérrez, Cerro Catedral",
    accommodationPrice: 65000,
    location: "https://maps.google.com/?q=-41.1335,-71.3103",
  },
  {
    id: 4,
    name: "Cancún",
    image: "https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?w=800",
    address: "Quintana Roo, México",
    weather: "Tropical cálido y húmedo todo el año",
    activities: "Playas paradisíacas, ruinas mayas, cenotes, snorkel, buceo, vida nocturna",
    accommodationPrice: 85000,
    location: "https://maps.google.com/?q=21.1619,-86.8515",
  },
  {
    id: 5,
    name: "Mendoza",
    image: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=800",
    address: "Cuyo, Mendoza, Argentina",
    weather: "Árido continental, veranos cálidos e inviernos fríos",
    activities: "Bodegas y vinos, alta montaña, Aconcagua, rafting, termas, esquí en Las Leñas",
    accommodationPrice: 42000,
    location: "https://maps.google.com/?q=-32.8895,-68.8458",
  },
  {
    id: 6,
    name: "Río de Janeiro",
    image: "https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=800",
    address: "Estado de Río de Janeiro, Brasil",
    weather: "Tropical atlántico, calor y humedad todo el año",
    activities: "Cristo Redentor, Pan de Azúcar, playas de Copacabana e Ipanema, samba, carnaval",
    accommodationPrice: 55000,
    location: "https://maps.google.com/?q=-22.9068,-43.1729",
  },
  {
    id: 7,
    name: "Punta del Este",
    image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800",
    address: "Maldonado, Uruguay",
    weather: "Templado oceánico, veranos cálidos",
    activities: "Playas exclusivas, casinos, La Mano en la arena, golf, vida nocturna, puerto",
    accommodationPrice: 95000,
    location: "https://maps.google.com/?q=-34.9489,-54.9574",
  },
  {
    id: 8,
    name: "Iguazú",
    image: "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=800",
    address: "Misiones, Argentina / Paraná, Brasil",
    weather: "Subtropical húmedo, calor y lluvias abundantes",
    activities: "Cataratas del Iguazú, Garganta del Diablo, paseos en lancha, selva misionera, safaris",
    accommodationPrice: 48000,
    location: "https://maps.google.com/?q=-25.6953,-54.4367",
  },
  {
    id: 9,
    name: "Cartagena de Indias",
    image: "https://images.unsplash.com/photo-1568632234157-ce7aecd03d0d?w=800",
    address: "Bolívar, Colombia",
    weather: "Tropical cálido y húmedo",
    activities: "Ciudad amurallada colonial, playas del Caribe, Islas del Rosario, gastronomía, rumba",
    accommodationPrice: 72000,
    location: "https://maps.google.com/?q=10.3910,-75.4794",
  },
  {
    id: 10,
    name: "Ushuaia",
    image: "https://images.unsplash.com/photo-1608633444449-db2c0148b768?w=800",
    address: "Tierra del Fuego, Argentina",
    weather: "Subpolar oceánico, frío todo el año",
    activities: "Fin del mundo, Parque Nacional Tierra del Fuego, Canal Beagle, pingüineras, glaciar Martial",
    accommodationPrice: 78000,
    location: "https://maps.google.com/?q=-54.8019,-68.3029",
  },
];
